### ISSUE TITLE
SWAMP-in-a-Box Docker image available?

### ISSUE THREAD

**Issue by tedmiston** [mirswamp/deployment#5]
Hi - I'm interested in running SWAMP-in-a-Box inside a Dockerized environment on Kubernetes (if it is possible).  I was wondering if an official Dockerfile or any Docker image of SWAMP-in-a-Box is available?  I did some initial searching but didn't find one.

/cc @brianaydemir2

**Comment by ghost** [comment]
Hi @tedmiston, 
SWAMP-in-a-Box currently does not have compatibility with containers, but our developers are looking into it, as containers are becoming increasingly popular. Please check back later or email us at support at continuousassurance dot org if you have further questions or suggestions.
Thanks!

**Comment by tedmiston** [comment]
Thank you @amillerswamp.  It sounds like we will go toward the VM route for now but we definitely look forward to containerization down the road.
